import { createSignal, For, Show } from 'solid-js'
import type { EcsJob, JobPdfReportMeta } from '../types/jobs'

interface JobConversationModalProps {
  job: EcsJob
  onClose: () => void
  onSendMessage: (jobId: string, message: string) => Promise<void>
  onDownloadReport: (job: EcsJob, reportCode?: JobPdfReportMeta['reportCode']) => void
}

export function JobConversationModal(props: JobConversationModalProps) {
  const [promptText, setPromptText] = createSignal('')
  const [isSending, setIsSending] = createSignal(false)

  const sendDirectMessage = async (msg: string) => {
    const trimmed = msg.trim()
    if (!trimmed || isSending()) return
    setIsSending(true)
    try {
      await props.onSendMessage(props.job.id, trimmed)
      setPromptText('')
    } finally {
      setIsSending(false)
    }
  }

  const handleSubmit = async (e: SubmitEvent) => {
    e.preventDefault()
    await sendDirectMessage(promptText())
  }

  const quickConversationStarters = () => [
    `What Airport Modernization services, live online sources, and calculations can you perform for ${props.job.airportIata}?`,
    `Fetch live online FAA & ADS-B telemetry for ${props.job.airportIata} and explain the key engineering metrics (no report needed).`,
    `Please generate the formal PDF assessment report for ${props.job.airportIata} using your PDF report tool.`,
  ]

  return (
    <div
      class="modal-backdrop"
      role="dialog"
      aria-modal="true"
      aria-labelledby="job-conversation-modal-title"
      onClick={(e) => {
        if (e.target === e.currentTarget) props.onClose()
      }}
    >
      <div class="modal-card modal-card-wide">
        <div class="modal-header">
          <div>
            <h2 id="job-conversation-modal-title" class="modal-title">
              Specialist Job Agent Conversation & PDF Report · {props.job.id} ({props.job.airportIata})
            </h2>
            <p class="modal-subtitle tabular-nums">
              {props.job.code} · {props.job.workflowName} · {props.job.ecsSystem} · State:{' '}
              {props.job.lifecycleState} ({props.job.progress}%)
            </p>
          </div>
          <div class="job-modal-header-actions">
            <Show
              when={(props.job.reports?.length ?? 0) > 0}
              fallback={
                <button
                  type="button"
                  class="btn-secondary"
                  disabled={isSending()}
                  onClick={() =>
                    sendDirectMessage(
                      `Please generate the formal PDF report for ${props.job.airportIata} (${props.job.title}) using your PDF report tool.`,
                    )
                  }
                >
                  {isSending() ? 'Running PDF Tool…' : 'Request PDF Report via Tool'}
                </button>
              }
            >
              <button
                type="button"
                class="btn-primary"
                onClick={() =>
                  props.onDownloadReport(
                    props.job,
                    props.job.reports?.[0]?.reportCode,
                  )
                }
              >
                Download {props.job.reports?.[0]?.reportCode} PDF Report
              </button>
            </Show>
            <button
              type="button"
              class="btn-secondary"
              onClick={() => props.onClose()}
            >
              Close
            </button>
          </div>
        </div>

        <div class="job-conversation-modal-body">
          <div class="job-purpose-box">
            <span class="job-section-label">Airport Modernization Mandate:</span>{' '}
            <span>{props.job.purpose}</span>
          </div>

          <div class="job-reports-bar">
            <div class="job-section-label">
              Tool-Generated PDF Assessment Report (Single Relevant Report per Request)
            </div>
            <div class="job-reports-list">
              <Show
                when={(props.job.reports?.length ?? 0) > 0}
                fallback={
                  <span class="modal-subtitle">
                    No PDF report generated yet — reports are only created by the{' '}
                    <code>generatePdfAssessmentReport</code> tool when required.
                  </span>
                }
              >
                <For each={props.job.reports}>
                  {(rep) => (
                    <button
                      type="button"
                      class="report-download-chip tabular-nums"
                      title={`Download ${rep.title} (Generated by generatePdfAssessmentReport Tool)`}
                      onClick={() => props.onDownloadReport(props.job, rep.reportCode)}
                    >
                      <svg
                        width="13"
                        height="13"
                        viewBox="0 0 16 16"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.75"
                        aria-hidden="true"
                      >
                        <path
                          d="M8 2.5v7.5m0 0L5.25 7.25M8 10l2.75-2.75M3 12.5h10"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        />
                      </svg>
                      <span>
                        {rep.reportCode} PDF · {rep.title}
                      </span>
                      <span class="report-chip-sub">({rep.fileName})</span>
                    </button>
                  )}
                </For>
              </Show>
            </div>
          </div>

          <div class="job-conversation-transcript">
            <div class="job-section-label">
              Specialist Job Agent Conversation ({props.job.chatHistory.length} messages)
            </div>
            <ul class="job-subchat-list job-subchat-list-modal">
              <For each={props.job.chatHistory}>
                {(msg) => (
                  <li class={`job-subchat-item role-${msg.role}`}>
                    <div class="job-subchat-meta tabular-nums">
                      <span>
                        {msg.role === 'user'
                          ? 'Operator / Airport Sponsor'
                          : `${props.job.workflowName} Specialist Agent`}
                      </span>
                      <span>{msg.timestamp}</span>
                    </div>
                    <div class="job-subchat-text">{msg.content}</div>
                  </li>
                )}
              </For>
            </ul>
          </div>

          <div class="prompt-starters" aria-label="Quick specialist agent questions">
            <For each={quickConversationStarters()}>
              {(starter) => (
                <button
                  type="button"
                  class="starter-chip"
                  disabled={isSending()}
                  onClick={() => sendDirectMessage(starter)}
                >
                  {starter}
                </button>
              )}
            </For>
          </div>

          <form class="job-conversation-form" onSubmit={handleSubmit}>
            <input
              type="text"
              class="conn-input"
              placeholder={`Converse with the ${props.job.workflowName} Agent for ${props.job.airportIata} (ask questions, run live calculations, or request a PDF report)…`}
              aria-label={`Message ${props.job.id} sub-conversation`}
              value={promptText()}
              onInput={(e) => setPromptText(e.currentTarget.value)}
            />
            <button
              type="submit"
              class="btn-primary"
              disabled={isSending() || !promptText().trim()}
            >
              {isSending() ? 'Agent Working…' : 'Send to Specialist Agent'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
