export interface UsSourceCitation {
  sourceId: string
  name: string
  url: string
  credibility: 1 | 2 | 3 | 4 | 5
  cadence: 'RT' | 'NRT' | 'BATCH'
  domain: string
}

export interface UsAirportBaseline {
  iata: string
  icao: string
  faaLid: string
  name: string
  cityState: string
  latitude: number
  longitude: number
  faaRegion: 'AEA' | 'ANE' | 'ASO' | 'AGL' | 'ACE' | 'ASW' | 'ANM' | 'AWP'
  hubClass: 'large_hub' | 'medium_hub' | 'small_hub'
  sponsorName: string
  rateRegime: 'residual' | 'compensatory' | 'hybrid'
  miiApprovalRequired: boolean
  enplanements: number
  annualOperationsTaf: number
  asvCapacityOps: number
  cpeUsd: number
  narePerPaxUsd: number
  dscrSenior: number
  dscrAllIn: number
  dcohDays: number
  pfcRateUsd: 4.5
  carrierHhi: number
  egridSubregion: string
  egridRateTonnesPerMWh: number
  fiveYearCapitalNeedUsdM: number
  fundedInstrumentsUsdM: number
}

export const US_AUTHORITATIVE_SOURCES: Record<string, UsSourceCitation> = {
  FAA_NPIAS: {
    sourceId: 'FAA_NPIAS',
    name: 'FAA National Plan of Integrated Airport Systems (NPIAS)',
    url: 'https://www.faa.gov/airports/planning_capacity/npias',
    credibility: 5,
    cadence: 'BATCH',
    domain: '5-Year Eligible Capital Needs & Statutory Hub Classification',
  },
  FAA_CATS_5100_127: {
    sourceId: 'FAA_CATS_5100_127',
    name: 'FAA CATS Form 5100-127 Operating & Financial Summary',
    url: 'https://cats.airports.faa.gov/',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Audited Aeronautical/Non-Aeronautical Revenue, O&M, CPE, DCOH, PFC',
  },
  MSRB_EMMA: {
    sourceId: 'MSRB_EMMA',
    name: 'MSRB EMMA Municipal Bond Official Statements & Feasibility Reports',
    url: 'https://emma.msrb.org/',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'GARB/PFC/CFC/PAB Debt Service, DSCR Covenants & AULA Rate Terms',
  },
  FAA_AIP_ATP: {
    sourceId: 'FAA_AIP_ATP',
    name: 'FAA AIP (49 U.S.C. § 47109) & IIJA Airport Terminal Program (ATP)',
    url: 'https://www.faa.gov/airports/aip/2026_aip_grants',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Federal Grant Shares (75%–95%), Obligations & Outlay Ratios',
  },
  FAA_AIP_BIL: {
    sourceId: 'FAA_AIP_BIL',
    name: 'FAA AIP Overview & IIJA Airport Terminal Program (ATP)',
    url: 'https://www.faa.gov/airports/aip/overview',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Statutory AIP Entitlements, Discretionary Grants & IIJA Terminal Funding',
  },
  FAA_PFC: {
    sourceId: 'FAA_PFC',
    name: 'FAA Passenger Facility Charge (14 CFR Part 158) & USASPENDING Awards',
    url: 'https://www.usaspending.gov/',
    credibility: 5,
    cadence: 'BATCH',
    domain: '$4.50 PFC Cap ($4.39 Net) & Federal Award Outlay Tracking',
  },
  FAA_AIPP_TIFIA: {
    sourceId: 'FAA_AIPP_TIFIA',
    name: 'FAA Airport Investment Partnership Program (49 U.S.C. § 47134) & USDOT TIFIA',
    url: 'https://www.transportation.gov/buildamerica',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Airport P3 Concessions, Privatization Exemptions & Low-Interest TIFIA Credit',
  },
  FAA_ADVISORY_CIRCULARS: {
    sourceId: 'FAA_ADVISORY_CIRCULARS',
    name: 'FAA Advisory Circulars (AC 150/5300-13B, 150/5360-13A, 150/5370-2G)',
    url: 'https://www.faa.gov/airports/resources/advisory_circulars',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Airfield Geometric Design, Terminal Planning & Live Operations CSPP Safety',
  },
  FAA_ADIP_5010: {
    sourceId: 'FAA_ADIP_5010',
    name: 'FAA Airport Data and Information Portal (ADIP / Form 5010 Master Record)',
    url: 'https://adip.faa.gov/',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Runway/Taxiway Geometry, Pavement Condition Index (PCI) & RSA Baselines',
  },
  FAA_TAF: {
    sourceId: 'FAA_TAF',
    name: 'FAA Terminal Area Forecast (TAF)',
    url: 'https://taf.faa.gov/',
    credibility: 5,
    cadence: 'BATCH',
    domain: '20-Year Official Enplanement & Aircraft Operations Forecast',
  },
  FAA_ASPM: {
    sourceId: 'FAA_ASPM',
    name: 'FAA Aviation System Performance Metrics (ASPM) & OPSNET',
    url: 'https://aspm.faa.gov/',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Facility Delay Attribution, Unimpeded Taxi Times & Hourly AAR/ADR',
  },
  FAA_SWIM: {
    sourceId: 'FAA_SWIM',
    name: 'FAA SWIM (SFDPS, TFMS, STDDS) & NAS Status API',
    url: 'https://nasstatus.faa.gov/api/airport-status-information',
    credibility: 5,
    cadence: 'RT',
    domain: 'Realtime NAS Flight Plans, Ground Delay Programs & Runway Closure Advisories',
  },
  FAA_NOTAM_SEARCH: {
    sourceId: 'FAA_NOTAM_SEARCH',
    name: 'FAA NOTAM Search & SWIM Active Construction Notices',
    url: 'https://notams.aim.faa.gov/notamSearch/',
    credibility: 5,
    cadence: 'RT',
    domain: 'Realtime Runway/Taxiway Closures, NAVAID Outages & AC 150/5370-2G Windows',
  },
  NOAA_AVIATION_WEATHER: {
    sourceId: 'NOAA_AVIATION_WEATHER',
    name: 'NOAA / NWS AviationWeather.gov Live METAR & TAF API',
    url: 'https://aviationweather.gov/data/api/',
    credibility: 5,
    cadence: 'RT',
    domain: 'Live Airport METAR Observations, Wind/Ceiling/Visibility & Construction Hold Triggers',
  },
  OPENSKY_NETWORK: {
    sourceId: 'OPENSKY_NETWORK',
    name: 'OpenSky Network Live ADS-B State Vectors API & FlightAware AeroAPI',
    url: 'https://opensky-network.org/data/api',
    credibility: 5,
    cadence: 'RT',
    domain: 'Live ADS-B Aircraft State Vectors, Terminal Airspace Traffic & Surface Movements',
  },
  FAA_BNATCS_GAO: {
    sourceId: 'FAA_BNATCS_GAO',
    name: 'FAA BNATCS Fact Sheet & GAO-26-107992 Oversight Audit',
    url: 'https://www.gao.gov/products/gao-26-107992',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'NAS ATC Modernization Lots ($12.5B Appropriated, Dec 2028 Phase-1 Target)',
  },
  TSA_PGDS_CBP_ATDS: {
    sourceId: 'TSA_PGDS_CBP_ATDS',
    name: 'TSA Planning Guidelines (PGDS) & CBP Airport Wait Times (awt.cbp.gov)',
    url: 'https://awt.cbp.gov/',
    credibility: 5,
    cadence: 'NRT',
    domain: 'Checkpoint CT/Touchless ID, CBIS & CBP Simplified Arrival FIS Wait Times',
  },
  BTS_TRANSTATS: {
    sourceId: 'BTS_TRANSTATS',
    name: 'USDOT BTS TranStats (T-100 & DB1B Market Share & Enplanements)',
    url: 'https://www.transtats.bts.gov/data_elements.aspx',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Certified Enplanements, Carrier HHI Concentration & O&D vs Connecting Split',
  },
  EPA_EGRID_AEDT: {
    sourceId: 'EPA_EGRID_AEDT',
    name: 'U.S. EPA eGRID Subregional Power Factors & FAA AEDT / VALE',
    url: 'https://www.epa.gov/egrid',
    credibility: 5,
    cadence: 'BATCH',
    domain: 'Subregional Grid CO2e Intensity & Gate Electrification APU Displacement',
  },
  TRB_ACRP_164: {
    sourceId: 'TRB_ACRP_164',
    name: 'TRB Airport Cooperative Research Program (ACRP Report 164 ORAT)',
    url: 'https://www.trb.org/ACRP/ACRP.aspx',
    credibility: 4,
    cadence: 'BATCH',
    domain: 'U.S. Operational Readiness and Airport Transfer (ORAT) Commissioning',
  },
  TRB_ACRP_ORAT: {
    sourceId: 'TRB_ACRP_ORAT',
    name: 'TRB ACRP Report 164 Operational Readiness & Airport Transfer (ORAT)',
    url: 'https://www.trb.org/ACRP/ACRP.aspx',
    credibility: 4,
    cadence: 'BATCH',
    domain: 'ORAT Trial Readiness Index (R >= 0.95), Systems Integration & Day-1 Cutover',
  },
  ACI_NA_NEEDS: {
    sourceId: 'ACI_NA_NEEDS',
    name: 'ACI-NA U.S. Airport Infrastructure Needs Study & Benchmarking',
    url: 'https://airportscouncil.org/advocacy/airport-infrastructure-funding/',
    credibility: 4,
    cadence: 'BATCH',
    domain: '$173.9B 5-Year U.S. Capital Need, PFC Advocacy & Hub Cohort Benchmarks',
  },
}

export const US_AIRPORT_BASELINES: Record<string, UsAirportBaseline> = {
  JFK: {
    iata: 'JFK',
    icao: 'KJFK',
    faaLid: 'JFK',
    name: 'John F. Kennedy International',
    cityState: 'New York, NY',
    latitude: 40.6413,
    longitude: -73.7781,
    faaRegion: 'AEA',
    hubClass: 'large_hub',
    sponsorName: 'Port Authority of NY & NJ (PANYNJ)',
    rateRegime: 'compensatory',
    miiApprovalRequired: false,
    enplanements: 31_450_000,
    annualOperationsTaf: 482_000,
    asvCapacityOps: 520_000,
    cpeUsd: 34.8,
    narePerPaxUsd: 19.4,
    dscrSenior: 2.15,
    dscrAllIn: 1.72,
    dcohDays: 490,
    pfcRateUsd: 4.5,
    carrierHhi: 2150,
    egridSubregion: 'NYCW',
    egridRateTonnesPerMWh: 0.392,
    fiveYearCapitalNeedUsdM: 19_000,
    fundedInstrumentsUsdM: 16_850,
  },
  DEN: {
    iata: 'DEN',
    icao: 'KDEN',
    faaLid: 'DEN',
    name: 'Denver International',
    cityState: 'Denver, CO',
    latitude: 39.8561,
    longitude: -104.6737,
    faaRegion: 'ANM',
    hubClass: 'large_hub',
    sponsorName: 'City & County of Denver Dept. of Aviation',
    rateRegime: 'hybrid',
    miiApprovalRequired: true,
    enplanements: 39_200_000,
    annualOperationsTaf: 675_000,
    asvCapacityOps: 810_000,
    cpeUsd: 13.9,
    narePerPaxUsd: 14.2,
    dscrSenior: 1.94,
    dscrAllIn: 1.48,
    dcohDays: 580,
    pfcRateUsd: 4.5,
    carrierHhi: 3180,
    egridSubregion: 'RMPA',
    egridRateTonnesPerMWh: 0.485,
    fiveYearCapitalNeedUsdM: 4_800,
    fundedInstrumentsUsdM: 4_120,
  },
  LAX: {
    iata: 'LAX',
    icao: 'KLAX',
    faaLid: 'LAX',
    name: 'Los Angeles International',
    cityState: 'Los Angeles, CA',
    latitude: 33.9416,
    longitude: -118.4085,
    faaRegion: 'AWP',
    hubClass: 'large_hub',
    sponsorName: 'Los Angeles World Airports (LAWA)',
    rateRegime: 'compensatory',
    miiApprovalRequired: true,
    enplanements: 37_800_000,
    annualOperationsTaf: 615_000,
    asvCapacityOps: 690_000,
    cpeUsd: 28.4,
    narePerPaxUsd: 17.8,
    dscrSenior: 2.08,
    dscrAllIn: 1.56,
    dcohDays: 540,
    pfcRateUsd: 4.5,
    carrierHhi: 1640,
    egridSubregion: 'CAMX',
    egridRateTonnesPerMWh: 0.214,
    fiveYearCapitalNeedUsdM: 14_200,
    fundedInstrumentsUsdM: 12_450,
  },
  ORD: {
    iata: 'ORD',
    icao: 'KORD',
    faaLid: 'ORD',
    name: 'Chicago O’Hare International',
    cityState: 'Chicago, IL',
    latitude: 41.9742,
    longitude: -87.9073,
    faaRegion: 'AGL',
    hubClass: 'large_hub',
    sponsorName: 'City of Chicago Department of Aviation (CDA)',
    rateRegime: 'residual',
    miiApprovalRequired: true,
    enplanements: 38_100_000,
    annualOperationsTaf: 745_000,
    asvCapacityOps: 880_000,
    cpeUsd: 24.6,
    narePerPaxUsd: 13.1,
    dscrSenior: 1.52,
    dscrAllIn: 1.28,
    dcohDays: 445,
    pfcRateUsd: 4.5,
    carrierHhi: 3420,
    egridSubregion: 'RFCW',
    egridRateTonnesPerMWh: 0.448,
    fiveYearCapitalNeedUsdM: 11_600,
    fundedInstrumentsUsdM: 9_820,
  },
  ATL: {
    iata: 'ATL',
    icao: 'KATL',
    faaLid: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International',
    cityState: 'Atlanta, GA',
    latitude: 33.6407,
    longitude: -84.4277,
    faaRegion: 'ASO',
    hubClass: 'large_hub',
    sponsorName: 'City of Atlanta Department of Aviation',
    rateRegime: 'hybrid',
    miiApprovalRequired: true,
    enplanements: 52_300_000,
    annualOperationsTaf: 795_000,
    asvCapacityOps: 920_000,
    cpeUsd: 5.85,
    narePerPaxUsd: 11.9,
    dscrSenior: 2.42,
    dscrAllIn: 1.88,
    dcohDays: 690,
    pfcRateUsd: 4.5,
    carrierHhi: 5840,
    egridSubregion: 'SRSO',
    egridRateTonnesPerMWh: 0.376,
    fiveYearCapitalNeedUsdM: 6_200,
    fundedInstrumentsUsdM: 5_550,
  },
  DFW: {
    iata: 'DFW',
    icao: 'KDFW',
    faaLid: 'DFW',
    name: 'Dallas/Fort Worth International',
    cityState: 'Dallas/Fort Worth, TX',
    latitude: 32.8998,
    longitude: -97.0403,
    faaRegion: 'ASW',
    hubClass: 'large_hub',
    sponsorName: 'DFW International Airport Board',
    rateRegime: 'hybrid',
    miiApprovalRequired: true,
    enplanements: 41_900_000,
    annualOperationsTaf: 710_000,
    asvCapacityOps: 850_000,
    cpeUsd: 14.7,
    narePerPaxUsd: 15.6,
    dscrSenior: 1.78,
    dscrAllIn: 1.42,
    dcohDays: 515,
    pfcRateUsd: 4.5,
    carrierHhi: 6420,
    egridSubregion: 'ERCT',
    egridRateTonnesPerMWh: 0.348,
    fiveYearCapitalNeedUsdM: 9_200,
    fundedInstrumentsUsdM: 8_100,
  },
  DCA: {
    iata: 'DCA',
    icao: 'KDCA',
    faaLid: 'DCA',
    name: 'Ronald Reagan Washington National',
    cityState: 'Arlington, VA',
    latitude: 38.8512,
    longitude: -77.0402,
    faaRegion: 'AEA',
    hubClass: 'large_hub',
    sponsorName: 'Metropolitan Washington Airports Authority (MWAA)',
    rateRegime: 'hybrid',
    miiApprovalRequired: true,
    enplanements: 12_800_000,
    annualOperationsTaf: 298_000,
    asvCapacityOps: 310_000,
    cpeUsd: 15.2,
    narePerPaxUsd: 14.1,
    dscrSenior: 1.86,
    dscrAllIn: 1.49,
    dcohDays: 560,
    pfcRateUsd: 4.5,
    carrierHhi: 2980,
    egridSubregion: 'RFCE',
    egridRateTonnesPerMWh: 0.295,
    fiveYearCapitalNeedUsdM: 1_450,
    fundedInstrumentsUsdM: 1_290,
  },
  SDF: {
    iata: 'SDF',
    icao: 'KSDF',
    faaLid: 'SDF',
    name: 'Louisville Muhammad Ali International',
    cityState: 'Louisville, KY',
    latitude: 38.1744,
    longitude: -85.736,
    faaRegion: 'ASO',
    hubClass: 'small_hub',
    sponsorName: 'Louisville Regional Airport Authority (LRAA)',
    rateRegime: 'residual',
    miiApprovalRequired: true,
    enplanements: 2_420_000,
    annualOperationsTaf: 178_000,
    asvCapacityOps: 245_000,
    cpeUsd: 9.4,
    narePerPaxUsd: 12.3,
    dscrSenior: 2.12,
    dscrAllIn: 1.78,
    dcohDays: 610,
    pfcRateUsd: 4.5,
    carrierHhi: 2340,
    egridSubregion: 'SRMW',
    egridRateTonnesPerMWh: 0.612,
    fiveYearCapitalNeedUsdM: 680,
    fundedInstrumentsUsdM: 590,
  },
  GEG: {
    iata: 'GEG',
    icao: 'KGEG',
    faaLid: 'GEG',
    name: 'Spokane International',
    cityState: 'Spokane, WA',
    latitude: 47.6199,
    longitude: -117.5338,
    faaRegion: 'ANM',
    hubClass: 'small_hub',
    sponsorName: 'Spokane Airport Board',
    rateRegime: 'hybrid',
    miiApprovalRequired: true,
    enplanements: 2_150_000,
    annualOperationsTaf: 72_000,
    asvCapacityOps: 140_000,
    cpeUsd: 8.65,
    narePerPaxUsd: 11.8,
    dscrSenior: 2.28,
    dscrAllIn: 1.91,
    dcohDays: 590,
    pfcRateUsd: 4.5,
    carrierHhi: 2490,
    egridSubregion: 'NWPP',
    egridRateTonnesPerMWh: 0.268,
    fiveYearCapitalNeedUsdM: 380,
    fundedInstrumentsUsdM: 325,
  },
}
